"""UpdateAnswerAndQuestionTable

Revision ID: cfdbb9c4a4e3
Revises: b7c00a688c2d
Create Date: 2025-11-20 15:26:18.292780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfdbb9c4a4e3'
down_revision: Union[str, Sequence[str], None] = 'b7c00a688c2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('answers', sa.Column('text', sa.Text(), nullable=False))
    op.alter_column('questions', 'text',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('questions', 'text',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=False)
    op.drop_column('answers', 'text')
    op.drop_column('answers', 'user_id')
    # ### end Alembic commands ###
